[build]
  # Set the base directory to the root (where the scripts exist)
  base = "/"
  # The directory where Netlify will publish the frontend build
  publish = "packages/trackingPortal/dist"
  # Command to install all packages and then build them from the root
  command = "yarn install && yarn build:shared && yarn build:frontend"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "yarn start"
  framework = "react"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true